### PR TITLE
changed code pick_val

### PR DESCRIPTION
**Pull request by KevinLin1016**

### CODE REVIEW

**Comment by bjones1** [comment]
Kevin,

Looks good. Rebase this, then comment here again.

**Comment by KevinLin1016** [comment]
Thank you Dr. Jones

**Comment by bjones1** [comment]
Kevin,

The rebase hasn't worked yet -- try to pull from my repo first.

**Comment by KevinLin1016** [comment]
Dr. Jones,

I rebased my branch, please check if it works.

Thank you

**Comment by bjones1** [comment]
Kevin,

Looks good. Your homework is complete.

**Pull request closed without merging**
