### PR TITLE
fixed spacing to make easier to read in hw1.py

### PR DESCRIPTION
**Pull request by pj11**

### CODE REVIEW

**Comment by bjones1** [comment]
I see the renamed branch, but not the rebase -- have you re-pulled from my repo to get the commit I made at 1:00 PM today?

**Comment by pj11** [comment]
In theory everything is right...?

**Comment by bjones1** [comment]
No, your rebase didn't work. Did you pull my latest commit first? Then do a rebase.

**Comment by pj11** [comment]
Something seems to be missing on my end.  I've set up your repository as a
remote, I've pulled from it and rebased, but nothing seems to be changing.

**Comment by bjones1** [comment]
Did you then push the result of the rebase back to your Github repo?

**Comment by pj11** [comment]
I did.

**Comment by bjones1** [comment]
Let's meet to figure this out. What are your free times Friday afternoon?

**Comment by bjones1** [comment]
If this helps, here's what I see. Your commits are based on some of my very old commits (toward the bottom). I want to see your commits on top of my newest commits at the top of the tree.

image

**Comment by pj11** [comment]
I'm free early Friday afternoon, around 1 or 2, maybe 2:30.

**Comment by bjones1** [comment]
OK. I'm free at 1:30 on Friday. Who are you? I don't recognize this userid.

**Comment by pj11** [comment]
Jeff Durst, down at ERDC.

**Comment by bjones1** [comment]
Jeff, thanks. I have a few minutes now, if you'd like to take a look, or we can meet (via Skype) on Friday at 1:30.

**Comment by pj11** [comment]
Just saw your email, I'm free at the moment.

**Comment by bjones1** [comment]
OK. my Skype is on -- give me a call.

**Comment by bjones1** [comment]
Fixed now. Your homework is complete.

**Pull request closed without merging**
