### PR TITLE
Added test_8 to the TestPickVal class

### PR DESCRIPTION
**Pull request by JawaJack**
I added a simple test to the TestPickVal class in order to try a pull request.

### CODE REVIEW

**Comment by bjones1** [comment]
Good progress. Please:

1. Let me know your netid, so I can identify you for grading.
2. Rebase your changes on the current code.
3. Make your changes in a new branch, instead of master.
4. Correct the test -- see the line notes I added.

**Comment by JawaJack** [comment]
My net ID is sjc314

**Comment by bjones1** [comment]
OK. I'm still not seeing the rebase, however...

**Comment by bjones1** [comment]
Closing this, since you've opened #18.

**Pull request closed without merging**
