### PR TITLE
Hw1

### PR DESCRIPTION
**Pull request by JawaJack**
Edited the test_8 function in the TestPickVal class

### CODE REVIEW

**Comment by bjones1** [comment]
Looks good. Rebase and then comment here and you're done.

**Comment by JawaJack** [comment]
I believe the rebase was successful. Let me know if anything else needs to be done.

**Comment by bjones1** [comment]
No, you haven't pulled my latest commits on which to rebase. Do that first.

**Comment by JawaJack** [comment]
I attempted to pull your latest commits and rebase.

**Comment by bjones1** [comment]
It looks like your master branch has the latest commits from my repo, but your hw1 branch doesn't. Rebase your hw1 branch and update this comment.

**Comment by JawaJack** [comment]
I just attempted to rebase my hw1 branch. It now says my hw1 branch is up to date. Was this rebase successful?

**Comment by bjones1** [comment]
Yes, partly -- you're up to date with my repo, but you need to add a commit to it.

**Pull request merged**
