### PR TITLE
More Information on *args and **kwargs

### PR DESCRIPTION
**Pull request by nw341**
Added a link for more information on **args and ***kwargs for hw4.

### CODE REVIEW

**Comment by bjones1** [comment]
Looks good. Would you:
1. Rebase to the current head.
2. Use another branch, not master, to make this pull request.

When that's done, comment here.

**Comment by nw341** [comment]
I have rebased and created another branch named HWargs and created another pull request.

**Comment by bjones1** [comment]
The rebase you did is still on top of a very old commit. First, find my newest commit (today at 4:25 PM), then rebase onto that.

**Comment by bjones1** [comment]
Done!

**Pull request closed without merging**
