### PR TITLE
Homework 1 Changes

### PR DESCRIPTION
**Pull request by jes520**
homework 1 changes

### CODE REVIEW

**Comment by bjones1** [comment]
Jamie,

Looks good. Would you:

1. Do you work on a different branch, instead of master.
2. Rebase this to the latest commits from my repo.

Comment here when that's done.

**Comment by jes520** [comment]
I believe that I just did a rebase? Hopefully?

**Comment by bjones1** [comment]
I see work on a different branch, but not the rebase. Pull from my repo first, then try again.

**Comment by jes520** [comment]
I think I've got it now!

**Comment by bjones1** [comment]
Looks good. Your homework is done.

**Pull request closed without merging**
