### PR TITLE
Updated Homework 1 File for Tyler Hannis, TJH153

### PR DESCRIPTION
**Pull request by TacoScientist**
Added my homework solution

### CODE REVIEW

**Comment by TacoScientist** [comment]
Homework Solution

**Comment by bjones1** [comment]
Please rebase.

**Comment by TacoScientist** [comment]
I believe I have everything complete and up to date, if this is incorrect please let me know. Also do I need to make another pull request?

**Comment by bjones1** [comment]
Tyler,

Looks good. You've completed homework 4, I'm not merging this since I already have a solution, though.

**Pull request closed without merging**
