### PR TITLE
Homework 4 Pull Request - Part 2

### PR DESCRIPTION
**Pull request by cstefanovic**
I'm not sure if this is what you wanted.  Trying to: "Move this pull request to another branch you create."

### CODE REVIEW

**Comment by bjones1** [comment]
Chris,

You have moved to a different branch, but I don't see the rebase. Pull from my repo and try the rebase again.

**Comment by cstefanovic** [comment]
Tried the rebase

**Comment by bjones1** [comment]
Your commits are made on top of my very old commits (red line). You want to move your commits on top of my current origin/master (blue line). Does that make sense?

image

**Comment by cstefanovic** [comment]
I realize now that I was pulling on smartgit for my repo and your repo as an upstream but I wasn't applying the changes from your repo to mine.  I'm having troubles doing that though, I am just making a mess of my local files

**Comment by bjones1** [comment]
Let's chat via Skype. Would 2:00 PM CST today work?

**Comment by cstefanovic** [comment]
Sorry I was out of town this weekend with limited internet access,  I think I figured out how to push from the remote/upstream repo to my local repo.

**Comment by bjones1** [comment]
Almost there. However, you're making edits on your master branch. Rebase to grad the latest, and put these edits in a different branch.

**Comment by cstefanovic** [comment]
Locally it looks like I am working on the branch that I created - My_Homework

screenshot 1

**Comment by bjones1** [comment]
You are, but this branch is based on **old** commits of mine (4-Sep); current commits were made yesterday just before class. Your master branch is based on this most recent commit, but your My_Homework branch isn't. Here's my view.

image

**Comment by cstefanovic** [comment]
Is the My_Homework branch on the most recent commit now?

**Comment by bjones1** [comment]
It looks like you ended up with a merge, but sometimes that's the only option. That's good enough.

**Pull request closed without merging**
